// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycxbJ652qRe0rhnpKKISNRwQUU7U4k5o',
    appId: '1:1056195894792:web:eec1660650aaed18be7bbd',
    messagingSenderId: '1056195894792',
    projectId: 'digtalhubsport',
    authDomain: 'digtalhubsport.firebaseapp.com',
    storageBucket: 'digtalhubsport.firebasestorage.app',
    measurementId: 'G-SLT54HKXZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN67wxmjrgx_8QuDE5ys97RMqf7CCxhDo',
    appId: '1:1056195894792:android:7d6ca406a3deea9dbe7bbd',
    messagingSenderId: '1056195894792',
    projectId: 'digtalhubsport',
    storageBucket: 'digtalhubsport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDG9R5wxdZ5x_PhKefazPesDgMccBeng',
    appId: '1:1056195894792:ios:7607d4c5d8eff273be7bbd',
    messagingSenderId: '1056195894792',
    projectId: 'digtalhubsport',
    storageBucket: 'digtalhubsport.firebasestorage.app',
    iosBundleId: 'com.example.degitalhubsport',
  );
}
